[package]
name = "steel"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
chrono = "0.4.24"
irc = "0.15.0"
irc-proto = "0.15.0"
futures = "0.3.28"
serde = "1.0.159"
serde_yaml = "0.9.19"
tokio = { version = "1.27.0", features = ["rt"] }
thiserror = "1.0.40"
simplelog = "0.12.1"
log = "0.4.17"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
time = { version = "0.3.20", features = ["macros"] }
percent-encoding = "2.2.0"
