[package]
name = "steel"
version = "0.7.10"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
winresource = "0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steel_core = { version = "0.1.4", path = "./crates/steel_core" }
glass = { version = "*", path = "./crates/glass", optional = true}

eframe = "0.25.0"
egui_extras = "0.25.0"

chrono = { version = "0.4.31", features = ["serde"] }
irc = "0.15.0"
irc-proto = "0.15.0"
futures = "0.3.30"
serde = "1.0.194"
serde_yaml = "0.9.30"
tokio = { version = "1.35.1", features = ["rt"] }
thiserror = "1.0.56"
simplelog = "0.12.1"
log = "0.4.20"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
time = { version = "0.3.31", features = ["macros"] }
percent-encoding = "2.3.1"
ureq = { version = "2.9.1", features = ["json", "native-tls"] }
flate2 = "1.0.28"
tar = "0.4.40"
zip = "0.6.6"
md5 = "0.7.0"

# Supporting library for rodio's "alsa-sys" dependency: librust-alsa-sys-dev
# TODO(TicClick): The fork is a workaround for Windows not respecting default audio device change.
# It can be removed along with TicClick/cpal once https://github.com/RustAudio/rodio/issues/463 is resolved.
rodio = { git = "https://github.com/TicClick/rodio.git", branch = "master" } # v0.17.3
png = "0.17.10"

libloading = "0.8.1"
winresource = "0.1.17"
serde_json = "1.0.111"

[features]
default = []
glass = ["dep:glass"]

[workspace]
members = [
    "./crates/steel_core",
]
