[package]
name = "steel_core"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# See also: https://github.com/emilk/egui/issues/2898
ecolor = "0.24.1"
chrono = { version = "0.4.24", features = ["serde"] }
irc-proto = "0.15.0"
serde = { version = "1.0.159", features = ["serde_derive"] }
serde_yaml = "0.9.19"
tokio = { version = "1.27.0", features = ["rt"] }
thiserror = "1.0.40"
simplelog = "0.12.1"
log = "0.4.17"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
time = { version = "0.3.20", features = ["macros"] }
percent-encoding = "2.2.0"
ureq = { version = "2.6.2", features = ["json", "native-tls"] }
