name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}

  upload-public-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Install Ubuntu dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: export DEBIAN_FRONTEND=noninteractive && sudo apt update && sudo apt install -y librust-alsa-sys-dev

      - name: Add fake empty dependency
        shell: bash
        run: crates/fake-glass.sh

      - name: Build and upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: steel
          token: ${{ secrets.GH_TOKEN }}

  upload-private-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Install Ubuntu dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: export DEBIAN_FRONTEND=noninteractive && sudo apt update && sudo apt install -y librust-alsa-sys-dev

      - name: Clone glass dependency
        uses: actions/checkout@v3
        with:
          repository: TicClick/glass
          path: crates/glass
          token: ${{ secrets.GH_TOKEN }}

      - name: Patch private dependencies' URLs
        shell: bash
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com".insteadOf ssh://git@github.com

      - name: Build (private)
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          dry-run: true
          bin: steel
          features: glass
        env:
          # https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli -- `git clone` uses private access token
          CARGO_NET_GIT_FETCH_WITH_CLI: true

      - name: Upload (private)
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python3 ./.github/push-private-asset.py \
            --uploads ${{ secrets.UPLOADS_METADATA_GIST }} \
            --releases ${{ secrets.RELEASES_METADATA_GIST }} \
            --tag ${{ github.ref_name }} \
            --filename $( ls steel-* ) \
            --catbox-hash ${{ secrets.CATBOX_HASH }}
