name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1.8.0
        with:
          token: ${{ secrets.GH_TOKEN }}

  upload-public-assets:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-15-intel  # x86_64
            target: x86_64-apple-darwin
          - os: macos-15  # aarch64 (ARM)
            target: aarch64-apple-darwin
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    needs: create-release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          target: ${{ matrix.target }}
          os: ${{ matrix.os }}
      - uses: taiki-e/upload-rust-binary-action@v1.18.0
        with:
          bin: steel
          token: ${{ secrets.GH_TOKEN }}
          target: ${{ matrix.target }}

  upload-private-assets:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-15-intel  # x86_64
            target: x86_64-apple-darwin
          - os: macos-15  # aarch64 (ARM)
            target: aarch64-apple-darwin
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    needs: create-release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          target: ${{ matrix.target }}
          os: ${{ matrix.os }}
          glass: real
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Build (private)
        uses: taiki-e/upload-rust-binary-action@v1.18.0
        with:
          dry-run: true
          bin: steel
          features: glass
          target: ${{ matrix.target }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Upload (private)
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SFTP_REMOTE_DIR: .
        run: |
          cd .github/asset-pusher
          uv run asset-pusher sftp \
              --host '${{ secrets.SFTP_HOST }}' \
              --port ${{ secrets.SFTP_PORT }} \
              --user '${{ secrets.SFTP_USER }}' \
              --password '${{ secrets.SFTP_PASSWORD }}' \
              --remote-dir '${{ env.SFTP_REMOTE_DIR }}' \
              --filename $( ls ../../steel-* ) \
              --tag ${{ github.ref_name }} \
              --releases ${{ secrets.RELEASES_METADATA_GIST }} \
              --uploads ${{ secrets.UPLOADS_METADATA_GIST }} \
              --http-base-url ${{ secrets.SFTP_HTTP_BASE_URL }}
